// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-FBmhWF8rsC_hY1fxIbPR2PCsJKcXlw',
    appId: '1:670792864283:web:42fc135b29332a33671ebe',
    messagingSenderId: '670792864283',
    projectId: 'tablebid-4e1f4',
    authDomain: 'tablebid-4e1f4.firebaseapp.com',
    storageBucket: 'tablebid-4e1f4.firebasestorage.app',
    measurementId: 'G-039MXZT6GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAACMXC5z8e1rDYrWlAfnGt-CWoDsZEH_A',
    appId: '1:670792864283:android:1fcd4ca854e16b6b671ebe',
    messagingSenderId: '670792864283',
    projectId: 'tablebid-4e1f4',
    storageBucket: 'tablebid-4e1f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLY-h56JbPx9inZ6jjctPyZoE9ZEshGBM',
    appId: '1:670792864283:ios:b92033c34767d9c0671ebe',
    messagingSenderId: '670792864283',
    projectId: 'tablebid-4e1f4',
    storageBucket: 'tablebid-4e1f4.firebasestorage.app',
    iosBundleId: 'com.lee.tablebid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLY-h56JbPx9inZ6jjctPyZoE9ZEshGBM',
    appId: '1:670792864283:ios:b92033c34767d9c0671ebe',
    messagingSenderId: '670792864283',
    projectId: 'tablebid-4e1f4',
    storageBucket: 'tablebid-4e1f4.firebasestorage.app',
    iosBundleId: 'com.lee.tablebid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAG-FBmhWF8rsC_hY1fxIbPR2PCsJKcXlw',
    appId: '1:670792864283:web:d31460bc4f726124671ebe',
    messagingSenderId: '670792864283',
    projectId: 'tablebid-4e1f4',
    authDomain: 'tablebid-4e1f4.firebaseapp.com',
    storageBucket: 'tablebid-4e1f4.firebasestorage.app',
    measurementId: 'G-L8DD6XEV29',
  );
}
